version: 2
jobs:
  build:
    docker:
      - image: circleci/php:8.0-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: /home/$CPANEL_USERNAME/public_html/.env $CPANEL_DIRECTORY
      - run: php artisan key:generate
      - run: php artisan config:cache
      - run: php artisan route:cache
      - run: php artisan view:cache
      - save_cache:
          key: laravel-config-v1-{{ checksum "composer.json" }}
          paths:
            - bootstrap/cache/config.php
            - bootstrap/cache/routes.php
            - bootstrap/cache/services.php
            - bootstrap/cache/packages.php
            - bootstrap/cache/packages-local.php

  deploy:
    docker:
      - image: circleci/php:8.0-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - laravel-config-v1-{{ checksum "composer.json" }}
      - run:
          name: Install SSH key
          command: |
            echo "$SSH_PRIVATE_KEY" > ssh_key
            chmod 600 ssh_key
            mkdir -p ~/.ssh
            mv ssh_key ~/.ssh/id_rsa
      - run:
          name: Deploy to cPanel
          command: |
            scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa -P $CPANEL_PORT $CIRCLE_WORKING_DIRECTORY/* $CPANEL_USERNAME@$CPANEL_SERVER:$CPANEL_DIRECTORY

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
