
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run: |
          if [ -n "$(git diff --name-only $CIRCLE_SHA1^1..$CIRCLE_SHA1)" ]; then
            git diff --name-only $CIRCLE_SHA1^1..$CIRCLE_SHA1 | xargs -I{} rsync -r --exclude=".git" --exclude="vendor" --exclude="node_modules" --exclude=".env" {} ./
          fi
      - run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - run: php artisan key:generate
      - run: php artisan config:cache
      - run: php artisan route:cache
      - run: php artisan view:cache

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run: echo "Deploying to production server"
      - run:
          name: Install SSH key
          command: |
            echo "$SSH_PRIVATE_KEY" > ssh_key
            chmod 600 ssh_key
            mkdir -p ~/.ssh
            mv ssh_key ~/.ssh/id_rsa
      - run:
          name: Deploy to cPanel
          command: |
            sshpass -p "$CPANEL_PASSWORD" rsync -avzhe ssh --delete --exclude='.env' --exclude='vendor/' --exclude='node_modules/' --exclude='.git/' --exclude='storage/' $CIRCLE_WORKING_DIRECTORY $CPANEL_USERNAME@$CPANEL_SERVER:$CPANEL_DIRECTORY

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
