version: 2
jobs:
  build:
    docker:
      - image: circleci/php:8.0-node-browsers
    steps:
      - checkout
      - run: |
          if [ -n "$(git diff --name-only $CIRCLE_SHA1^1..$CIRCLE_SHA1)" ]; then
            for file in $(git diff --name-only $CIRCLE_SHA1^1..$CIRCLE_SHA1); do
          if [ -f "$file" ]; then
            scp -r -i $SSH_PRIVATE_KEY_PATH -o StrictHostKeyChecking=no "$file" $CPANEL_USER@$CPANEL_SERVER:/home/$CPANEL_user/public_html/deploy/
          elif [ -d "$file" ]; then
            scp -r -i $SSH_PRIVATE_KEY_PATH -o StrictHostKeyChecking=no "$file/" $CPANEL_USER@$CPANEL_SERVER:/home/$CPANEL_user/public_html/deploy/"$file"
          fi
          done
          fi

      - run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - run: php artisan key:generate
      - run: php artisan config:cache
      - run: php artisan route:cache
      - run: php artisan view:cache

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Install SSH key
          command: |
            echo "$SSH_PRIVATE_KEY" > ssh_key
            chmod 600 ssh_key
            mkdir -p ~/.ssh
            mv ssh_key ~/.ssh/id_rsa
      - run:
          name: Deploy to cPanel
          command: |
           scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa -P $CPANEL_PORT $CIRCLE_WORKING_DIRECTORY/* $CPANEL_USERNAME@$CPANEL_SERVER:$CPANEL_DIRECTORY

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
